<?php

namespace Taichi\BlogBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesCount()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('COUNT(c.id)');

        return $qb->getQuery()->getResult();
    }
}
