<?php

namespace Taichi\BlogBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsCount()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('COUNT(c.id)');

        return $qb->getQuery()->getResult();
    }

    public function getCommentsPerMonth($begin, $end)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('COUNT(c.id)')
            ->where('c.createdAt BETWEEN :begin AND :end')
            ->setParameter('begin', $begin)
            ->setParameter('end', $end);

        return $qb->getQuery()->getResult();
    }
}
