<?php

namespace Taichi\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Taichi\BlogBundle\Entity\Category;
use Taichi\BlogBundle\Entity\Tag;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getAllPosts()
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'c', 't', 'co')
            ->join('p.category', 'c')
            ->leftJoin('p.tags', 't')
            ->leftJoin('p.comments', 'co')
            ->orderBy('p.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function getAllPostsByCategory(Category $category)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 't', 'co')
            ->leftJoin('p.tags', 't')
            ->leftJoin('p.comments', 'co')
            ->where('p.category = :category')
            ->orderBy('p.createdAt', 'DESC')
            ->setParameter('category', $category);

        return $qb->getQuery()->getResult();
    }

    public function getAllPostsByTag(Tag $tag)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p', 'c', 'co')
            ->join('p.category', 'c')
            ->leftJoin('p.tags', 't')
            ->leftJoin('p.comments', 'co')
            ->where('t = :tag')
            ->orderBy('p.createdAt', 'DESC')
            ->setParameter('tag', $tag);

        return $qb->getQuery()->getResult();
    }
}