<?php

namespace Taichi\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\Cache;
use Taichi\BlogBundle\Entity\Category;
use Taichi\BlogBundle\Entity\Tag;

/**
 * PostRepository
 * @Cache()
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getAllPosts()
    {
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param Category $category
     * @return array
     */
    public function getAllPostsByCategory(Category $category)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.category = :category')
            ->orderBy('p.createdAt', 'DESC')
            ->setParameter('category', $category);

        return $qb->getQuery()->getResult();
    }

    /**
     * @param Tag $tag
     * @return array
     */
    public function getAllPostsByTag(Tag $tag)
    {
        $qb = $this->createQueryBuilder('p')
            ->where(':tag MEMBER OF p.tags')
            ->orderBy('p.createdAt', 'DESC')
            ->setParameter('tag', $tag);

        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function getPostsCount()
    {
        $qb = $this->createQueryBuilder('p')
            ->select('COUNT(p.id)');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param \DateTime $begin
     * @param \DateTime $end
     * @return array
     */
    public function getPostsPerMonth(\DateTime $begin, \DateTime $end)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('COUNT(p.id)')
            ->where('p.createdAt BETWEEN :begin AND :end')
            ->setParameter('begin', $begin)
            ->setParameter('end', $end);

        return $qb->getQuery()->getResult();
    }
}