<?php

namespace Taichi\BlogBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository implements \Countable
{
    public function count()
    {
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT t
            FROM TaichiBlogBundle:Tag t
            ')
        ;

        $paginator = new Paginator($query);

        return count($paginator);
    }
}
