<?php

namespace Taichi\BlogBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsersCount()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('COUNT(u.id)');

        return $qb->getQuery()->getResult();
    }
}
