taichi_blog:
    resource: "@TaichiBlogBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    prefix:   /
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%

