taichi_user:
    resource: "@TaichiUserBundle/Controller/"
    type:     annotation
    prefix:   /

taichi_blog:
    resource: "@TaichiBlogBundle/Controller/"
    type:     annotation
#    prefix:   /{_locale}
#    prefix:   /
#    requirements:
#        _locale: %app_locales%
#    defaults:
#        _locale: %locale%
#

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
