# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    slugger:
        class: Taichi\BlogBundle\Utils\Slugger

    # These are the Twig extensions that create new filters and functions for
    # using them in the templates
