parameters:
    taichi_blog.sitemap.listener.class: Taichi\BlogBundle\EventListener\SitemapListener

services:
    taichi.blog.menu_builder:
        class: Taichi\BlogBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
              # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createAdminSidebarMenu, alias: admin_sidebar }

    taichi.blog.menu_renderer:
        # The class implements Knp\Menu\Renderer\RendererInterface
        class: Taichi\BlogBundle\Menu\TaichiRenderer
        arguments: [%kernel.charset%] # set your own dependencies here
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.renderer, alias: taichi }

    admin.category:
        class: Taichi\BlogBundle\Admin\CategoryAdmin
        arguments: [~, Taichi\BlogBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'label.blog', label: label.category }

    admin.tag:
        class: Taichi\BlogBundle\Admin\TagAdmin
        arguments: [~, Taichi\BlogBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'label.blog', label: label.tag }

    admin.post:
        class: Taichi\BlogBundle\Admin\PostAdmin
        arguments: [~, Taichi\BlogBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'label.blog', label: label.post }

    my.sitemap.listener:
        class: %taichi_blog.sitemap.listener.class%
        arguments: ['@router']
        tags: [{name: "presta.sitemap.listener"}]