services:
#    taichi_user.example:
#        class: Taichi\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    taichi_user.registration.form.type:
        class: Taichi\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: taichi_user_registration }